### ISSUE TITLE
One-line install failing on Osx (Yosemite)

### ISSUE THREAD

**Issue by gustavoper** [twolfson/sexy-bash-prompt#51]
I`m having this error when trying to run the one line install on my OSX 10.10.2 (Yosemite). I googled a lot but can't find any successful results. Here's the log: 

      remote: Counting objects: 328, done.
      remote: Compressing objects: 100% (208/208), done.
      remote: Total 328 (delta 31), reused 307 (delta 30) 
      Receiving objects: 100% (328/328), 120.38 KiB | 0 bytes/s, done.
      Resolving deltas: 100% (31/31), done.
      Checking connectivity... done.
      # Copying .bash_prompt to ~/.bash_prompt
      cp -f .bash_prompt ~/.bash_prompt
      ./install.bash
      # Adding ~/.bash_prompt to ~/.bashrc
      FATAL: Profile script not found.
      make: *** [install] Error 1

**Comment by twolfson** [comment]
This means you have none of `~/.bash_profile`, `~/.bash_login`, nor `~/.profile`. We do not write to `/etc` to prevent undesired results.

https://github.com/twolfson/sexy-bash-prompt/blob/0.24.2/install.bash#L21-L35

To fix this, try running:

```bash
touch ~/.bashrc
```

before running the one line install script.

**Comment by jackson-sandland** [comment]
The script looks like it attempts to add to bash_profile. Try using:
touch ~/.bash_profile
That worked here!

**Comment by twolfson** [comment]
Heh, I mistyped it and nobody corrected me until now. Thanks for the correction @jackson-sandland =)

**Comment by jackson-sandland** [comment]
@twolfson You're very welcome :+1:

**Comment by gustavoper** [comment]
That was weird, because I remembered that I have made this comment too. 

In that time, I created .bashrc and it didn't worked. Then, I created .bash_profile and it worked like a charm.

Sorry, I should have double-checked my response. 
Thanks!
