### ISSUE TITLE
Weird behavior when running 'zsh'

### ISSUE THREAD

**Issue by gustavoper** [twolfson/sexy-bash-prompt#55]
When running 'zsh' on ITerm2, I got that weird messages. 

![201511_error](https://cloud.githubusercontent.com/assets/1050263/10869394/bdeb49b0-8095-11e5-9bd2-f10a1f396f73.png)
 
Note that I hit Enter a few times just to see if message disappears, but it's still there.

I`m using OSX  (10.11.1) El Captan.

**Comment by rpdelaney** [comment]
sexy-bash-prompt is for, well, bash after all. Did you try setting a new PS1 in your zshrc?

**Comment by twolfson** [comment]
Another possibility is that we installed to `~/.profile` due to `~/.bash_profile` and `~/.bash_login` not existing.

https://github.com/twolfson/sexy-bash-prompt/blob/0.26.1/install.bash#L29-L31

**Comment by rpdelaney** [comment]
Hmm. Would this be a basis for handling that situation differently?

**Comment by twolfson** [comment]
Possibly, still waiting to hear back from @gustavoper to see if that's actually the problem.

**Comment by gustavoper** [comment]
Oh, sorry for being too late. But I tried almost everything, but it only worked after a full reinstall of Iterm2 and applying all updates.
Now it's wokting like a charm.

**Comment by twolfson** [comment]
Weird. Alright, thanks for the bug report =)

**Comment by barretV** [comment]
somehow I'm getting this issue tried removing iterm and reinstalling but no luck, even installed beta versions. it worked fine at first but I accidentally ran the script twice and that's when it looked messed up and I can't get it back no matter what I do even following uninstall methods. very strange. if anyone else has this figured out let me know


UPDATE: found the solution, used this and it works
https://github.com/stevenwenxu/sexy-zsh-prompt/tree/zsh
