### ISSUE TITLE
Not change the PS1

### ISSUE THREAD

**Issue by Mte90** [twolfson/sexy-bash-prompt#60]
Is possible to not change the PS1 output of the shell?
in my case is:
`mte90@siduction:~$`
but with that became
`#`

**Comment by twolfson** [comment]
Unfortunately, the prompt operates by overriding PS1. It's unclear but did you want help debugging or uninstalling `sexy-bash-prompt`?

**Comment by Mte90** [comment]
Only how to change the code so the PS1 remain like the original but only the git commands will be colorful.

**Comment by twolfson** [comment]
I still don't understand. What do you mean by "the original" and "git commands will be colorful"? Can you provide examples?

**Comment by Mte90** [comment]
With that software I get
```
root at siduction in /tmp
# quit
```
but the original on my system is
```
root@siduction:/tmp#
```

**Comment by twolfson** [comment]
Ah, I see so you want the coloring but not the "at"/"in"/multiline format.

**Comment by twolfson** [comment]
I can think of 2 options:

- Fork the repo and customize it as you want (a lot of people do this)
- Run the normal `.bash_prompt` and then override `PS1` again with your custom format
    - Here is our reference PS1 https://github.com/twolfson/sexy-bash-prompt/blob/0.26.4/.bash_prompt#L258-L269
    - The default bash prompt PS1 can be found in `/etc/bashrc`
        - `PS1='\h:\W \u\$ '`
    - More details can be found under PROMPTING in `man bash`
        - http://linux.die.net/man/1/bash

**Comment by Mte90** [comment]
Ok thanks for the info.
In my case is `'${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '`

**Comment by Mte90** [comment]
```
PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$( sexy_bash_prompt_is_on_git && \
  echo -n \" \[$sexy_bash_prompt_preposition_color\]on\[$sexy_bash_prompt_reset\] \" && \
  echo -n \"\[$sexy_bash_prompt_git_status_color\]\$(sexy_bash_prompt_get_git_info)\" && \
  echo -n \"\[$sexy_bash_prompt_git_progress_color\]\$(sexy_bash_prompt_get_git_progress)\" && \
  echo -n \"\[$sexy_bash_prompt_preposition_color\]\")\[$sexy_bash_prompt_reset\]\
\[$sexy_bash_prompt_symbol_color\]$sexy_bash_prompt_symbol \[$sexy_bash_prompt_reset\]"
```
Ok now i have changed in that way and is perfect for my needs.

**Comment by twolfson** [comment]
Wonderful, I'm glad to hear it all worked out. Thanks for posting your result so others can reuse it =)
