### ISSUE TITLE
optionally display user.name and user.email 

### ISSUE THREAD

**Issue by szydan** [twolfson/sexy-bash-prompt#61]
Hi 
First thanks for the awesome project

I work with many repositories and have to commit the code as different users. 
Quite often if I forget to set specific 

```
git config user.name "name"
git config user.email "email"
```

I make the commit under my global username and email. Then later I have to fix the commits rewrite github history etc.
For me seeing under which username and email is currently set would be very useful.
I'm wandering if others would also like such functionality.
It could be optional, and disabled by default as most people would like their prompt to be as short as possible.

**Comment by twolfson** [comment]
Unfortunately, there are a lot of ways someone can customize their shell so customizing for everyone's desires is impractical. I suggest you either:

- Fork the repo and customize it as you want (a lot of people do this)
- Run the normal `.bash_prompt` and then override `PS1` again with your custom format
    - This would be done in your `~/.bashrc` after we run `. ~/.bash_prompt`
    - Here is our reference PS1 https://github.com/twolfson/sexy-bash-prompt/blob/0.26.4/.bash_prompt#L258-L269
