### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by ggcarvalho** [twolfson/sexy-bash-prompt#65]
Hey, Todd.
Could you give directions to uninstall as well? 
Thanks, mate.

**Comment by twolfson** [comment]
To uninstall `sexy-bash-prompt`, we would follow the reverse of `install.sh`

https://github.com/twolfson/sexy-bash-prompt/blob/0.26.5/install.bash

The instructions would be:

- Remove `. ~/.bash_prompt` from either `~/.bashrc`
- Remove `~/.bash_prompt` from file system
    - Done via `rm ~/.bash_prompt`
- We additionally add a `~/.bashrc` invocation to one of `~/.bash_profile`, `~/.bash_login`, or `~/.profile` but it depends on what currently exists
    - https://github.com/twolfson/sexy-bash-prompt/blob/0.26.5/install.bash#L21-L35

I think we should probably add this to the documentation so I'll leave this issue open until that happens

**Comment by twolfson** [comment]
We have added uninstall documentation in `0.26.6`. Thanks for the bug report!
