### ISSUE TITLE
Branch with multiple remotes always appears unpushed?

### ISSUE THREAD

**Issue by abhijit86k** [twolfson/sexy-bash-prompt#68]
On one of my repos I have set up two remotes (redundancy). Even after pushing to both remotes, the prompt indicates 'unpushed' status. I haven't had time to look into this yet with a clean test case, so it may just be some quirk on my repo.

**Comment by twolfson** [comment]
We have hardcoded to `origin` as the remote to compare to as that's the `git` convention. What are your remotes named?

If neither of them is named `origin` but you have branch tracking set up, there's probably a way to resolve remote based on the branch itself.

**Comment by abhijit86k** [comment]
My remotes were called <server1> <server2> and "usb". I tried renaming <server1> to origin using
git remote rename, but that didn't seem to change anything. I'll try to look into it over the weekend.

**Comment by twolfson** [comment]
Ah, weird. As a heads up GitHub is hiding the `<server1>`/`<server2>` due to thinking they were HTML tags =/

**Comment by abhijit86k** [comment]
Updated the comment. I was wondering what happened :)

**Comment by abhijit86k** [comment]
"git remote rename" does work. In any case, there can be cases where there are multiple remotes and the default tracking branches differ. I've added the check and created a pull request.

**Comment by twolfson** [comment]
Forgot to close this. This has been resolved via #69 and #70 and released in `0.27.0`
