### ISSUE TITLE
Opt-in flags for extensions

### ISSUE THREAD

**Issue by rpdelaney** [twolfson/sexy-bash-prompt#81]
In #80 we discussed developing a system of opt-in flags for extensions to the prompt, which would allow users to enable features like exit code reporting or long-running process timers.

Discuss implementation details here. How should we do this?

**Comment by rpdelaney** [comment]
In #81 I suggested some env vars for enabling status reporting. If the user sets those variables, doesn't that count as opt-in? Or do we need a separate boolean to say "yes I want it"?

**Comment by twolfson** [comment]
Ah, sorry. I might have not made it clear in #80, while it still feels like a good extension mechanism, we have no use cases for them yet -- exit code reporting and long-running process timers should be always on to start, then if people complain we can build out opt-in/opt-out functionality
