### ISSUE TITLE
error when loading sexy bash prompt

### ISSUE THREAD

**Issue by gnzsnz** [twolfson/sexy-bash-prompt#96]
Hi,

I call .bash_prompt from my bashrc file and  I get an error.

`bash_prompt` is located in `.config/bash_prompt` and i call it like this in my .bashrc file
```bash
# sexy bash prompt
# https://github.com/twolfson/sexy-bash-prompt
[ -f ~/.config/bash_prompt ] && source ~/.config/bash_prompt
# end sexy bash prompt
```
For information, my `.bash_profile` is sourcing `.bashrc`

This is the error message right after login, and after any command
```
Last login: Sat Sep  3 13:49:52 2022 from 10.227.123.1
Missing `sexy_bash_prompt_exit_code` for prompt symbol coloring
Please verify `PROMPT_COMMAND` includes `sexy_bash_prompt_command` (enabled unless overwritten)
ubuntu at primary in ~
$ ls
dotfiles  Home  snap  tmp
Missing `sexy_bash_prompt_exit_code` for prompt symbol coloring
Please verify `PROMPT_COMMAND` includes `sexy_bash_prompt_command` (enabled unless overwritten)
ubuntu at primary in ~
$ source .config/bash_prompt
ubuntu at primary in ~
$
```

however if i load manually again bash_prompt, then it seems to work
```
ubuntu at primary in ~
$ source .config/bash_prompt
ubuntu at primary in ~
$
```
i don't get an error anymore. I can reproduce the error in osx (using brew.sh gnu bash) and ubuntu 20.04

I'm i missing anything?

**Comment by gnzsnz** [comment]
from what i see, PROMPT_COMMAND does not contains "sexy_bash_prompt_exit_code" right after login

```
Last login: Sat Sep  3 13:47:42 on ttys000
Missing `sexy_bash_prompt_exit_code` for prompt symbol coloring
Please verify `PROMPT_COMMAND` includes `sexy_bash_prompt_command` (enabled unless overwritten)
gonzo at Gonzalos-MacBook-Pro in ~
$ echo $PR
$PROMPT_COMMAND  $PROMPT_DIRTRIM
gonzo at Gonzalos-MacBook-Pro in ~
$ echo $PROMPT_COMMAND
history -a
Missing `sexy_bash_prompt_exit_code` for prompt symbol coloring
Please verify `PROMPT_COMMAND` includes `sexy_bash_prompt_command` (enabled unless overwritten)
gonzo at Gonzalos-MacBook-Pro in ~
$ . .config/bash_prompt
gonzo at Gonzalos-MacBook-Pro in ~
$ echo $PROMPT_COMMAND
sexy_bash_prompt_command ; history -a
gonzo at Gonzalos-MacBook-Pro in ~
$

```

and it's set after I manually source bash_prompt again. hope this helps

**Comment by twolfson** [comment]
Based on these lines, I'm guessing your `~/.bashrc` has some lines to set `PROMPT_COMMAND` after you `source ~/.config/bash_prompt`

```
Last login: Sat Sep  3 13:47:42 on ttys000
Missing `sexy_bash_prompt_exit_code` for prompt symbol coloring
Please verify `PROMPT_COMMAND` includes `sexy_bash_prompt_command` (enabled unless overwritten)
gonzo at Gonzalos-MacBook-Pro in ~
$ echo $PR
$PROMPT_COMMAND  $PROMPT_DIRTRIM
gonzo at Gonzalos-MacBook-Pro in ~
$ echo $PROMPT_COMMAND
history -a
```

i.e. `~/.config/bash_prompt` should have set an extended `PROMPT_COMMAND` as per linked code below:

https://github.com/twolfson/sexy-bash-prompt/blob/1.1.0/.bash_prompt#L300-L318

**Comment by gnzsnz** [comment]
Hi,

thanks for your reply. indeed that solved the issue. i moved the line to source bash_prompt to the end of my bashrc and now it works fine. thanks again.
